language: node_js


install: 
  - npm install

script:
  - hexo g
  - hexo d -g

# after_script:
#   - cd ./public
#   - git init
#   - git config user.name "hirayclay"
#   - git config user.email "2425875132@qq.com"
#   - git add .
#   - git commit -m "update post"
#   - git push --force --quiet "http://HirayClay.github.io" master

env:
 global:
   - GH_REF: git@github.com:HirayClay/HirayClay.github.io.git


    
